In [1]:
imoort numpy as np

SyntaxError: invalid syntax (<ipython-input-1-ac0944926d2b>, line 1)

In [2]:
import numpy as np

In [3]:
my_arr=np.arange(1000000)

In [4]:
my_arr=np.arange(1000000)

In [5]:
%time for _ in range(10): my_arr = my_arr * 2

Wall time: 25.6 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 96.2 ms


In [7]:
data = np.random.randn(2,3)

In [8]:
data

array([[-0.00317501, -0.41638621, -0.88939768],
       [ 0.75483709, -0.35154096, -0.25919739]])

In [9]:
data*10

array([[-0.03175005, -4.16386212, -8.8939768 ],
       [ 7.54837087, -3.51540963, -2.59197393]])

In [10]:
data+data

array([[-0.00635001, -0.83277242, -1.77879536],
       [ 1.50967417, -0.70308193, -0.51839479]])

In [11]:
data.shape

(2, 3)

In [12]:
data.ndim

2

In [13]:
data1 = [6,7.5,8,0,1]

In [14]:
arr1 = np.array(data1)

In [15]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [16]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr2.dtype

dtype('int32')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros((3,6)).ndim

2

In [25]:
np.zeros((2,3,2)).ndim

3

In [26]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr = np.array([1,2,3,4,5])

In [28]:
arr.dtype

dtype('int32')

In [29]:
float_arr = arr.astype(np.float64)

In [30]:
float_arr.dtype

dtype('float64')

In [31]:
arr = np.array([3.7,-1.2,-2.6,0.5,12.9,10.1])

In [32]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [33]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [34]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype = np.string_)

In [35]:
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [36]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [37]:
int_arry = np.arange(10)

In [38]:
int_arry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
calibers = np.array([.22,.270,.357,.380,.44,.50],dtype = np.float64)

In [40]:
int_arry.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
empty_uint32 = np.empty(8,dtype = 'u4')

In [42]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [43]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [44]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [46]:
arr * 0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [47]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

In [48]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [49]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [50]:
arr = np.arange(10)

In [51]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr[5]

5

In [53]:
arr[5:8

SyntaxError: unexpected EOF while parsing (<ipython-input-53-8016d9d4bb8c>, line 1)

In [54]:
arr[5:8]

array([5, 6, 7])

In [55]:
arr[5:8] = 12

In [56]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [57]:
arr_slice = arr[5:8]

In [58]:
arr_slice

array([12, 12, 12])

In [59]:
arr_slice[1] = 12345

In [60]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [61]:
arr_slice[:] = 64

In [62]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [63]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [64]:
arr2d[2]

array([7, 8, 9])

In [65]:
arr2d[0][2]

3

In [66]:
arr2d[0,2]

3

In [67]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [68]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
old_values = arr3d[0].copy()

In [71]:
arr3d[0] = 42

In [72]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr3d[1,0]

array([7, 8, 9])

In [74]:
x = arr3d[1]

In [75]:
x[0]

array([7, 8, 9])

In [77]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [78]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [79]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [82]:
arr2d[1,:2]

array([4, 5])

In [83]:
arr2d[:2,2]

array([3, 6])

In [84]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [85]:
arr2d[:2,1:] = 0

In [86]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [87]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [88]:
data = np.random.randn(7,4)

In [89]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [90]:
data

array([[-0.1350534 ,  0.16672576, -1.78810364,  0.5199834 ],
       [-0.42692752,  1.27666513, -0.56678125,  1.8118995 ],
       [-0.91170022,  0.45000401,  0.47122795, -0.06170854],
       [ 0.56063194,  1.16271203,  0.18660991, -1.0877288 ],
       [ 0.72061948, -0.14877854,  1.4312685 , -1.04884204],
       [ 0.60405916, -1.20374226,  0.64212931,  1.09130836],
       [-0.21870375, -1.23155078,  0.47807046,  0.06398921]])

In [91]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [92]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [93]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [94]:
data[names == 'Bob']

array([[-0.1350534 ,  0.16672576, -1.78810364,  0.5199834 ],
       [ 0.56063194,  1.16271203,  0.18660991, -1.0877288 ]])

In [95]:
data[names == 'Bob',2:]

array([[-1.78810364,  0.5199834 ],
       [ 0.18660991, -1.0877288 ]])

In [96]:
data[names == 'Bob',3]

array([ 0.5199834, -1.0877288])

In [97]:
names !=  'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [98]:
data[~(names == 'Bob')]

array([[-0.42692752,  1.27666513, -0.56678125,  1.8118995 ],
       [-0.91170022,  0.45000401,  0.47122795, -0.06170854],
       [ 0.72061948, -0.14877854,  1.4312685 , -1.04884204],
       [ 0.60405916, -1.20374226,  0.64212931,  1.09130836],
       [-0.21870375, -1.23155078,  0.47807046,  0.06398921]])

In [99]:
cond = names == 'Bob'

In [100]:
data[~cond

SyntaxError: unexpected EOF while parsing (<ipython-input-100-adf7fa06a9d8>, line 1)

In [101]:
data[~cond]

array([[-0.42692752,  1.27666513, -0.56678125,  1.8118995 ],
       [-0.91170022,  0.45000401,  0.47122795, -0.06170854],
       [ 0.72061948, -0.14877854,  1.4312685 , -1.04884204],
       [ 0.60405916, -1.20374226,  0.64212931,  1.09130836],
       [-0.21870375, -1.23155078,  0.47807046,  0.06398921]])

In [102]:
mask = (names == 'Bob') | (names == 'Will')

In [103]:
mask

array([ True, False,  True,  True,  True, False, False])

In [104]:
data[mask]

array([[-0.1350534 ,  0.16672576, -1.78810364,  0.5199834 ],
       [-0.91170022,  0.45000401,  0.47122795, -0.06170854],
       [ 0.56063194,  1.16271203,  0.18660991, -1.0877288 ],
       [ 0.72061948, -0.14877854,  1.4312685 , -1.04884204]])

In [105]:
data[data < 0] = 0

In [106]:
data

array([[0.        , 0.16672576, 0.        , 0.5199834 ],
       [0.        , 1.27666513, 0.        , 1.8118995 ],
       [0.        , 0.45000401, 0.47122795, 0.        ],
       [0.56063194, 1.16271203, 0.18660991, 0.        ],
       [0.72061948, 0.        , 1.4312685 , 0.        ],
       [0.60405916, 0.        , 0.64212931, 1.09130836],
       [0.        , 0.        , 0.47807046, 0.06398921]])

In [107]:
data[names != 'Joe'] = 7

In [108]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.27666513, 0.        , 1.8118995 ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.60405916, 0.        , 0.64212931, 1.09130836],
       [0.        , 0.        , 0.47807046, 0.06398921]])

In [109]:
arr = np.empty((8,4))

In [111]:
for i in range(8):
arr[i] = i

IndentationError: expected an indented block (<ipython-input-111-d3fc949faa10>, line 2)

In [112]:
for i in range(8):
  arr[i] = i

In [113]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [114]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [115]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [116]:
arr = np.arange(32).reshape((8,4))

In [117]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [118]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [119]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [120]:
arr = np.arange(15).reshape((3,5))

In [121]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [122]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [123]:
arr = np.random.randn(6,3)

In [124]:
arr

array([[-0.92303942, -0.35660517,  0.1878475 ],
       [ 0.76340007, -0.56641593, -1.41788726],
       [-1.34861895, -0.4740822 , -0.31065374],
       [-0.19297054,  0.82553402, -0.7230245 ],
       [-0.06485434,  0.56665164, -0.79938217],
       [ 0.19449333,  0.17948821, -0.40614352]])

In [125]:
np.dot(arr.T, arr)

array([[ 3.33282589,  0.3749706 , -0.72447874],
       [ 0.3749706 ,  1.70756469, -0.23934857],
       [-0.72447874, -0.23934857,  3.46892557]])

In [126]:
arr = np.arange(16).reshape((2,2,4))

In [127]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [128]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [129]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [130]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])